# Generated by Django 3.2.8 on 2021-10-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='Untitled Board', max_length=100, unique=True),
        ),
    ]
