# Generated by Django 3.2.8 on 2021-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211030_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
