# Generated by Django 3.2.8 on 2021-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211103_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
